### ISSUE TITLE
Unhandled Exception: setState() called after dispose()

### ISSUE THREAD

**Issue by tajjacob** [iamriajul/adhan-dart#1]
Salam brother..
thanks for developing this package..
.
I have this error when running the example even though the pray time is generated.
'
Hope you can address this issue.

`E/flutter (29148): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: setState() called after dispose(): _TodayKuliahMasjidWaktuSolatPageState#fe309(lifecycle state: defunct, not mounted)
E/flutter (29148): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (29148): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (29148): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
`
![image](https://user-images.githubusercontent.com/63710008/91638508-a7ab8b80-ea42-11ea-886e-848d08c26947.png)

![image](https://user-images.githubusercontent.com/63710008/91638553-f6f1bc00-ea42-11ea-8c27-08d4f47f38e9.png)

**Comment by iamriajul** [comment]
Waalaikumussalam brother,
can you try this: 
`
  bool isDisposed = false;

  @override
  void initState() {
    isDisposed = false;
    getLocationData().then((locationData) {
      if (isDisposed) {
        return;
      }
      if (locationData != null) {
        setState(() {
          prayerTimes = PrayerTimes(
              Coordinates(locationData.latitude, locationData.longitude),
              DateComponents.from(DateTime.now()),
              CalculationMethod.karachi.getParameters());
        });
      } else {
        setState(() {
          locationError = "Couldn't Get Your Location!";
        });
      }
    });

    super.initState();
  }


  @override
  void dispose() {
    isDisposed = true;
    super.dispose();
  }

`
