### ISSUE TITLE
Support maghrib angle

### ISSUE THREAD

**Issue by phoenix-lab-io** [iamriajul/adhan-dart#11]
Assalam 3alaykom,
First of all, thanks for this nice package, it works like a charm and the documentation is really nice.

While implementing your package in my app, I noticed the calculation method of Tehran wasn't available, so I tried to implement the CalculationParameters myself, but I realised that the maghribAngle wasn't implemented in this Dart.

Would it be possible to implement it inshaAllah ?
Here's the JS version: https://github.com/batoulapps/adhan-js/blob/master/src/CalculationParameters.js

Many thanks!

**Comment by iamriajul** [comment]
InShaAllah, can you try making a pull request on this, create a branch for your feature and commits and then push and then create a pull request? I'm little busy nowadays.

**Comment by phoenix-lab-io** [comment]
The feature is done, but I don't have the right access, how should I do the PR ? 
Thanks!
