### ISSUE TITLE
Dart null safety support

### ISSUE THREAD

**Issue by iamriajul** [iamriajul/adhan-dart#14]
Dart null safety: https://dart.dev/null-safety

**Comment by Anas35** [comment]
If there is no WIP for migrating this package to null-safety, I would happy to make a PR.

**Comment by iamriajul** [comment]
> If there is no WIP for migrating this package to null-safety, I would happy to make a PR.

You're welcome, you can make a PR.
Jazhaka Allahu Khairan.

**Comment by Anas35** [comment]
Look like three package doesn't support **Null-Safety**
- strings
- dart_numerics
- test_coverage 

migrating a package without the null safety packages that depend on this package is discouraged.

Should we wait for these three projects to migrate?

**Comment by iamriajul** [comment]
I think we should wait.

**Comment by iamriajul** [comment]
although they are only dev dependencies, this package has no dependencies other than dev dependencies.

**Comment by iamriajul** [comment]
I think we can migrate only the lib folder (not test and bin).

**Comment by Anas35** [comment]
I think we can remove `Strings` package and we can find a workaround. It hasn't been used much in this project.
As for `dart_numeric`, the last update was in 2018.

**Comment by Anas35** [comment]
> I think we can migrate only the lib folder (not test folder).

I don't think we can do that. If the lib folder changed, test might have some error.

**Comment by iamriajul** [comment]
As said Dart 2 is sound null safety, which means nullsafety code can be used from non-nullsafe code, they can co-exist. I think should we shouldn't worry about the test, the test should run fine.

**Comment by Anas35** [comment]
Ah! I get it. Will send a PR by tomorrow.

**Comment by iamriajul** [comment]
Published as prerelease: https://pub.dev/packages/adhan/versions/2.0.0-nullsafety.0
Try it out in your projects. and give feedback.
