### ISSUE TITLE
App continuedly waiting for location 

### ISSUE THREAD

**Issue by uni-united** [iamriajul/adhan-dart#2]
Hi

I tried the code from ur example in Git... bit the app is continuously waiting to fetch location. Not getting the output
![WhatsApp Image 2020-09-27 at 6 29 33 PM](https://user-images.githubusercontent.com/56224355/94365552-97dda080-00ef-11eb-8b7e-8e994aa7f813.jpeg)

**Comment by uni-united** [comment]
Please address this issue at the earliest

**Comment by iamriajul** [comment]
Your Phone's GPS/Location service may be slow or turned off, and it has nothing to do with the actual library itself.
