### ISSUE TITLE
Summer time 

### ISSUE THREAD

**Issue by moosalim** [iamriajul/adhan-dart#20]
Hello brother

Does this package adjust prayer times with regard to summer time variation?

**Comment by iamriajul** [comment]
Does this help?: https://github.com/batoulapps/adhan-java/issues/25#issuecomment-792790308
As adhan-dart is following adhan-java.

**Comment by moosalim** [comment]
@iamriajul 

this comment is about **fixed angles for calculating Fajr & Isha** not Summer time

**Comment by iamriajul** [comment]
moonsighting_committee method automatically makes adjustments based on the season. All you need to do is calculate times using that method.

**Comment by moosalim** [comment]
Thanks 
but what about my question about summer time?

Does this package adjust prayer times with regard to summer time variation?

**Comment by iamriajul** [comment]
I think it does adjust based on summer variations. and about summer, summer is a season, so it does adjust that.

**Comment by iamriajul** [comment]
and also the library goes through a heavy real-life data test, which ensures correctness of result. Checkout test data here: https://github.com/iamriajul/adhan-dart/tree/master/test/data/prayer-times

**Comment by iamriajul** [comment]
I think you got your answer, So closing issue now, You may open this issue if you need.

**Comment by moosalim** [comment]
Thanks bother
