### ISSUE TITLE
can't get the times displayed

### ISSUE THREAD

**Issue by AekaderFELLAGUE** [iamriajul/adhan-dart#21]
Salam Alaykum.
when I enter the app with the location service disable, I get a dialog to allow the service, when I tap ok it is not updating the screen and keeps saying "Waiting for Your Location..." !!!

**Comment by iamriajul** [comment]
Waalaikumussalam.
That is not related to the library itself. It is related with the example flutter app provided, you may download the example and edit that or fix bug as you wish without any restrictions.
Thanks.

**Comment by AekaderFELLAGUE** [comment]
Bro, can you give the right example, I really need it
