### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by MZDN** [iamriajul/adhan-dart#25]
I noticed that the adhan-dart is giving plus 1hr for Asr time. For example I was expecting to give 17:15 instead of 18:15. 
Do you know why? 

`final params = CalculationMethod.karachi.getParameters();`
`params.madhab = Madhab.hanafi;`
 `prayerTimes = PrayerTimes.today(myCoordinates, params,
  utcOffset: _dateTime.timeZoneOffset);`

**Comment by iamriajul** [comment]
Assalamualaikum,
You might want to change the Madhab. as Asr calculations vary much by Madhab.
**Another thing to keep in mind: If you want the PrayerTime result in your device timezone then don't pass utc-offset.**
Thanks.

**Comment by MZDN** [comment]
That fix it. Many thanks @iamriajul !
