### ISSUE TITLE
[Question] Show Fajr for the next day after Isha

### ISSUE THREAD

**Issue by vuln3r** [iamriajul/adhan-dart#28]
# Please follow the general troubleshooting steps first:

- [x] I've Read the official [README v1](https://github.com/iamriajul/adhan-dart/blob/master/README.md) or [README v2](https://github.com/iamriajul/adhan-dart/blob/v2/README.md)?
- [x] I've Read the official [API reference](https://pub.dev/documentation/adhan/latest/adhan/adhan-library.html)?

**Question related to which version**: Common

### Description

I have a question about Isha prayer exactly after Isha prayer.  So once Isha is done I'm getting a `none` enum case and I want to show Fajr for the next day.. I tried with:

` void _getPrayersForTomorrow() {
    var newDate = new DateTime(nextPrayerTime.value.year,
        nextPrayerTime.value.month, nextPrayerTime.value.day + 1);
    nextPrayer.value = prayerTimes.value.nextPrayerByDateTime(newDate);
  }`
  
  but I still get `none` as praying time... is there any workaround to archive that? 
  
  Selam

**Comment by iamriajul** [comment]
Yes, I've implemented a workaround for this scenario, but that's in Kotlin.
You may get ideas from Kotlin codes too.
Workaround: https://gist.github.com/iamriajul/2cdbc15d4fd0e8bad203205c9302a54b

**Comment by vuln3r** [comment]
Oh, thanks for it :) it helps a lot 👍🏻
