### ISSUE TITLE
Time Prayer not Show

### ISSUE THREAD

**Issue by Nanank-kho** [iamriajul/adhan-dart#3]
time prayer not show,.
only text waiting for your location.

thanks

**Comment by iamriajul** [comment]
Your Phone's GPS/Location service may be slow or turned off, and it has nothing to do with the actual library itself.
Duplicate: https://github.com/iamriajul/adhan-dart/issues/2#issuecomment-700518681

**Comment by iamriajul** [comment]
Duplicate of #2
