### ISSUE TITLE
How to get offset of a country. because when we pass offset it give correct time for manual lat lng. if we did not pass offset for manual lat lng it give wrong timings. also clarify that offset is necessary for manual location.  

### ISSUE THREAD

**Issue by HamadBangash353** [iamriajul/adhan-dart#30]
# Please follow the general troubleshooting steps first:

- [x] I've Read the official [README v1](https://github.com/iamriajul/adhan-dart/blob/master/README.md) or [README v2](https://github.com/iamriajul/adhan-dart/blob/v2/README.md)?
- [x] I've Read the official [API reference](https://pub.dev/documentation/adhan/latest/adhan/adhan-library.html)?

**Question related to which version**: [eg: v1, v2, common]

### Description

[Describe the question and your situation]

**Comment by iamriajul** [comment]
You can try to use the official timezone library: https://pub.dev/packages/timezone

**Comment by iamriajul** [comment]
Other useful resources related to the question: https://stackoverflow.com/questions/16086962/how-to-get-a-time-zone-from-a-location-using-latitude-and-longitude-coordinates
