### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Saliim17** [iamriajul/adhan-dart#35]
# Please follow the general troubleshooting steps first:

- [x] I've Read the official [README v1](https://github.com/iamriajul/adhan-dart/blob/master/README.md) or [README v2](https://github.com/iamriajul/adhan-dart/blob/v2/README.md)?
- [x] I've Read the official [API reference](https://pub.dev/documentation/adhan/latest/adhan/adhan-library.html)?

**Question related to which version**: 2.0.0-nullsafety.2

### Description
Is there any method that returns the remaining time to the next prayer? Looking at the documentation, I only see that I can get the current date but nothing else.

**Comment by iamriajul** [comment]
Assalamualaikum,
Brother you can just easily calculate  remaining time yourself in Dart. 
```dart
final remainingTimeDifference = DateTime.now().difference(prayerTimes.fajr)
```
Thanks.
