### ISSUE TITLE
Midnight calculation

### ISSUE THREAD

**Issue by admincode1** [iamriajul/adhan-dart#51]
Midnight calculation should be from Isha (end of sun light) to Fajr (beginning of sun light) / 2 not from Maghrib to Fajr  / 2.
I hope this help developer in the next update.

**Comment by JMApps** [comment]
The calculation of the last third of the night comes from the Maghrib prayer, since the night of a new day begins precisely after Maghrib.

**Comment by admincode1** [comment]
> The calculation of the last third of the night comes from the Maghrib prayer, since the night of a new day begins precisely after Maghrib.

Maybe that's how the calculation of the last third of night is calculated and I totally agree that new day begins after Maghrib.
But my concern is the Middle of night calculation is calculated incorrectly, perhaps that Maghrib time is 5pm & Isha time is 7PM and Fajr time is 5AM, Middle of the night should be 12AM not 11PM.
