### ISSUE TITLE
Adhan package Return wrong time on different timezone

### ISSUE THREAD

**Issue by ariona** [iamriajul/adhan-dart#53]
**Describe the bug**
Adhan package return wrong prayer times, it added two hour to real time/other prayer time app.

**To Reproduce**
1. Set Coordinate to: -6.2297419, 106.7594778
2. Set Date Time on device to Indonesia, Time Zone Jayapura (GMT+09:00)
3. Set params to 
```dart
CalculationParameters(
    madhab: Madhab.shafi,
    fajrAngle: 20,
    ishaAngle: 18,
    highLatitudeRule: HighLatitudeRule.twilight_angle,
)
```
4. get prayer times using PrayerTimes class
5. prayer times return +2 hours

**Screenshots**
Here is the screenshot from my app
<img width="300" alt="Screenshot 2023-12-18 at 14 57 31" src="https://github.com/iamriajul/adhan-dart/assets/752483/6655e2b9-862f-49b9-8de5-a6c900293f71">

And here is screenshot of prayer times of same city on online prayer time
<img width="500" alt="Screenshot 2023-12-18 at 14 58 09" src="https://github.com/iamriajul/adhan-dart/assets/752483/3c036074-96ce-4d6c-b3cb-cb9f71a54812">

You can see that this package return +2 hours to the desired time

**Environment(please complete the following information):**
 - Dart Language Version: 3.1.3
 - Flutter Version:  3.13.6,
 - Adhan-Dart Version: 2.0.0+1

**Comment by iamriajul** [comment]
@ariona how did you solve your issue?

**Comment by ariona** [comment]
Turn out the coordinate variable didn't update with the requested location
😔

It should be working now, Jazakallah..
