### ISSUE TITLE
CalculationMethod.egyptian has wrong fajrAngle and ishaAngle

### ISSUE THREAD

**Issue by m-alwakeel** [iamriajul/adhan-dart#8]
CalculationMethod.egyptian fajrAngle is 20.0 and ishaAngle is 18.0 but they should be 19.5 and 17.5 instead.

**Comment by iamriajul** [comment]
@m-alwakeel where did you find this: 19.5 and 17.5?

**Comment by m-alwakeel** [comment]
In your README 😄 

<img width="893" alt="SS" src="https://user-images.githubusercontent.com/78014922/108027024-25d00e80-7032-11eb-92fe-f3ae28cc0425.png">

**Comment by iamriajul** [comment]
Issue related to this: https://github.com/batoulapps/adhan-java/issues/14

**Comment by iamriajul** [comment]
PR related to this on adhan-java: https://github.com/batoulapps/adhan-java/pull/29
